# Generated by Django 4.1.5 on 2023-01-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtsmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deudores',
            name='deuda_inicial_en_dolares',
            field=models.FloatField(default=0),
        ),
    ]
