# Generated by Django 4.1.5 on 2023-01-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtsmanager', '0002_deudores_deuda_inicial_en_dolares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudores',
            name='deuda_inicial_en_dolares',
            field=models.FloatField(),
        ),
    ]
