# Generated by Django 4.1.5 on 2023-02-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtsmanager', '0004_alter_deudores_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudores',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
