# Generated by Django 4.1.5 on 2023-02-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtsmanager', '0005_alter_deudores_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudores',
            name='deuda_inicial_en_dolares',
            field=models.FloatField(blank=True),
        ),
    ]
