# Generated by Django 4.1.5 on 2023-02-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtsmanager', '0006_alter_deudores_deuda_inicial_en_dolares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudores',
            name='created_at',
            field=models.DateField(),
        ),
    ]
